
import { GalleryGrid } from "./gallery-grid"

export const metadata = {
  title: 'Gallery',
  description: 'Watch some of my works.',
}

export default function Page() {
  return (
    <section>
      <h1 className="font-semibold text-2xl mb-4 tracking-tighter">my gallery </h1>
      <div className="iframe-container lang">
      <p className="pb-4"> Here there are some personal projects i made while learning or just for fun, 
        there are no professional and them are all open-source for those who want to see the code and use it.</p>
        <iframe src="https://kaio-rama.github.io/visualsloosers/" className="web-example"></iframe>
        <label className="font-semibold mb-8 tracking-tighter"> Visual Loosers - Visual editor running on JavaScript & GLSL</label>
      <p className="mb-0">
        <i>Visual generator using GLSL code.
        You can start seeing results with the "Random" button, which "generates" random codes
        (pre-established and generated by AI) to help you get familiar with the app interface.</i>  
      </p>
      <a href="https://kaio-rama.github.io/visualsloosers/" target="blank" className="text-indigo-300">Visual Looser preview.</a>

      
      <iframe src="https://kaio-rama.github.io/whereToBeer/" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter"> WhereToBeer - Web Application made on pure JavaScript</label>
      <p className="mb-0">
        <i>WTB means to be a web-application wich get acces on your location and gives you closest bars, coffee shops & restaurants where you can go.
           It borns from the idea of makin a cultural agenda, but just for the mockup I used this "where to beer" idea.</i>  
      </p>
      <a href="https://kaio-rama.github.io/whereToBeer/" target="blank" className="text-indigo-300">WhereToBeer preview on GitHub pages.</a>

      </div>

      <div className="iframe-container lang" hidden>
      <p className="pb-4">Aquí hay algunos proyectos personales que hice mientras aprendía o simplemente por diversión, no hay ninguno profesional 
        y todos son de código abierto para aquellos que quieran ver el código y usarlo.</p>
        <iframe src="https://kaio-rama.github.io/visualsloosers/" className="web-example"></iframe>
        <label className="font-semibold mb-8 tracking-tighter"> Visual Loosers - Visual editor running on JavaScript & GLSL</label>
      <p className="mb-0">
        <i> Generador de visuales mediante código GLSL.
              Puedes empezar a ver resultados con el botón “Random”, que “genera” códigos aleatorios
              (preestablecidos y generados por IA) para ayudar a familiarizarte con la interfaz de la aplicación.</i>  
      </p>
      <a href="https://kaio-rama.github.io/visualsloosers/" target="blank" className="text-indigo-300">Visual Looser en GitHub pages.</a>

      
      <iframe src="https://kaio-rama.github.io/whereToBeer/" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter"> WhereToBeer - Aplicación web hecha en JavaScript puro.</label>
      <p className="mb-0">
        <i>WTB es una aplicación web que te permite conocer tu ubicación y te indica los bares, cafeterías y restaurantes más cercanos a los que puedes ir.
           Surge de la idea de crear una agenda cultural, pero solo para la maqueta utilicé la idea de "dónde tomar una cerveza".</i>  
      </p>
      <a href="https://kaio-rama.github.io/whereToBeer/" target="blank" className="text-indigo-300">Ver WhereToBeer en GitHub pages.</a>

      </div>
      <GalleryGrid/>
    </section>
  )
}