
import { GalleryGrid } from "./gallery-grid"

export const metadata = {
  title: 'Gallery',
  description: 'Watch some of my works.',
}

export default function Page() {
  return (
    <section>
      <h1 className="font-semibold text-2xl mb-4 tracking-tighter">my gallery </h1>
      <div className="iframe-container lang">
      <p className="pb-4"> Here there are some personal projects I've made while learning or just for fun, 
        them are not professional and them are all open-source for those who want to see the code and use it.</p> 
        <iframe src="https://kaio-rama.github.io/visualsloosers/" className="web-example"></iframe>
        <label className="font-semibold mb-8 tracking-tighter"> Visual Loosers - Visual editor running on JavaScript & GLSL</label>
      <p className="mb-0">
        <i>Visual generator using GLSL code.
        You can start seeing results with the "Random" button, which "generates" random codes
        (pre-established and generated by AI) to help you get familiar with the app interface.</i>  
      </p>
      <a href="https://kaio-rama.github.io/visualsloosers/" target="blank" className="text-indigo-300">Visual Looser preview.</a>

      <iframe src="https://dbd-mastodon-ece15jveo-kaio-ramas-projects.vercel.app/home" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter"> DBD Mastodon - Project of interface for Mastodon social network using Astro.</label>
      <p className="mb-0">
        <i>DBD Mastodon is a web application that allows you to access your Mastodon social network and interact with it.
           It's an open source project of interface for Mastodon social network, but it's on a really early stage of development.
           It's started as an experiment to learn how to develop a web application rendering only HTML with Astro , and it's still in development.
           Anyway in the proccess I figure it out 1 - how to use the Mastodon API and how to interact with it and 2- it's probably best to use react, next.js or
           some other framework with SSR (Server Side Rendering) to render the HTML and interact with the API.
           </i>
      </p>
      <a href="https://dbd-mastodon-ece15jveo-kaio-ramas-projects.vercel.app/home" target="blank" className="text-indigo-300">DBD Mastodon preview on Vercel .</a>


      <iframe src="https://kaio-rama.github.io/whereToBeer/" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter"> WhereToBeer - Web Application made on pure JavaScript</label>
      <p className="mb-0">
        <i>WTB means to be a web-application wich get acces on your location and gives you closest bars, coffee shops & restaurants where you can go.
           It borns from the idea of makin a cultural agenda, but just for the mockup I used this "where to beer" idea.</i>  
      </p>
      <a href="https://kaio-rama.github.io/whereToBeer/" target="blank" className="text-indigo-300">WhereToBeer preview on GitHub pages.</a>

      
      <iframe src="https://kaio-rama.github.io/gif-app/" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter">  Gif searcher - using React & Giffy API. </label>
      <p className="mb-0">
        <i>Simple web application made with React that accesses the Giffy API to search for gifs based on an input given by the user.
        This is the app I started with in React and an example of calls to an external API </i>  
      </p>
      <a href="https://kaio-rama.github.io/gif-app/" target="blank" className="text-indigo-300">Gif Searcher on GitHub pages.</a>
      
      <h3 className="mt-20 font-bold"> Art & Design gallery:</h3>
      <p> As I said, I'm not only a front-end developer and designer. I'm really into art.
        Most of my "art works" are related to audiovisual. I've directed some shortfilms and videoclips and used to work on cinema industry
        as a prop manager in the art department in Netflix, Star+ (a.k.a Disney) & HBO series, movies and publicities.
        At this time I find more interest on working as developer, and let the art to my personal projects.
        Here there are just some of all the works I'vde done. You can find others on my Behance or my Linkedin, 
        but they are focus on these "artist works" more than to software developing.       
      </p>

      </div>

      <div className="iframe-container lang" hidden>
      <p className="pb-4">Aquí hay algunos proyectos personales que hice mientras aprendía o simplemente por diversión, no hay ninguno profesional 
        y todos son de código abierto para aquellos que quieran ver el código y usarlo.</p>
        <iframe src="https://kaio-rama.github.io/visualsloosers/" className="web-example"></iframe>
        <label className="font-semibold mb-8 tracking-tighter"> Visual Loosers - Visual editor running on JavaScript & GLSL</label>
      <p className="mb-0">
        <i> Generador de visuales mediante código GLSL.
              Puedes empezar a ver resultados con el botón “Random”, que “genera” códigos aleatorios
              (preestablecidos y generados por IA) para ayudar a familiarizarte con la interfaz de la aplicación.</i>  
      </p>
      <a href="https://kaio-rama.github.io/visualsloosers/" target="blank" className="text-indigo-300">Visual Looser en GitHub pages.</a>

      <iframe src="https://dbd-mastodon-ece15jveo-kaio-ramas-projects.vercel.app/home" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter"> DBD Mastodon - Proyecto de interfaz para Mastodon usando Astro.</label> 
      <p className="mb-0">
        <i>DBD Mastodon es una aplicación web que te permite acceder a tu red social Mastodon e interactuar con ella.
           Es un proyecto de interfaz de código abierto para la red social Mastodon, esta en una fase muy temprana de desarrollo.
           Comenzó como un experimento para aprender a desarrollar una aplicación web que renderice solo HTML con Astro, y todavía está en desarrollo.
           De todos modos, en el proceso descubrí 1: cómo usar la API de Mastodon y cómo interactuar con ella y 2: probablemente sea mejor usar React, NEXT.js o
           algún otro framework con SSR (Server Side Rendering) para renderizar el HTML e interactuar con la API.
           </i>
      </p>
      <a href="https://dbd-mastodon-ece15jveo-kaio-ramas-projects.vercel.app/home" target="blank" className="text-indigo-300">DBD Mastodon BETA en Vercel .</a>
      
      <iframe src="https://kaio-rama.github.io/whereToBeer/" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter"> WhereToBeer - Aplicación web hecha en JavaScript puro.</label>
      <p className="mb-0">
        <i>WTB es una aplicación web que te permite conocer tu ubicación y te indica los bares, cafeterías y restaurantes más cercanos a los que puedes ir.
           Surge de la idea de crear una agenda cultural, pero solo para la maqueta utilicé la idea de "dónde tomar una cerveza".</i>  
      </p>
      <a href="https://kaio-rama.github.io/whereToBeer/" target="blank" className="text-indigo-300">Ver WhereToBeer en GitHub pages.</a>

      <iframe src="https://kaio-rama.github.io/gif-app/" className="web-example mt-8"></iframe>
      <label className="font-semibold mb-8 tracking-tighter">  Gif searcher - aplicación web con React & la API de Giffy.</label>
      <p className="mb-0">
        <i>Simple aplicación web hecha en React y que accede a la API de Giffy para buscar gifs en base a un input que le pase el usuario.
          Es la app con la que empecé en React y un ejemplo de llamadas a una API externa. </i>  
      </p>
      <a href="https://kaio-rama.github.io/gif-app/" target="blank" className="text-indigo-300">Ver Gif Searcher en GitHub pages.</a>

      <h3 className="mt-20 font-bold"> Art & Design gallery:</h3>
      <p> Como dije, no solo soy un desarrollador y diseñador front-end. Me gusta mucho el arte.
        La mayoría de mis "obras de arte" están relacionadas con el audiovisual. He dirigido algunos cortometrajes y videoclips, y solía trabajar en la industria cinematográfica
        como encargado de utilería en el departamento de arte en series, películas y publicidades de Netflix, Star+ (Disney) y HBO.
        En este momento encuentro más interés en trabajar como desarrollador y dejo el arte para mis proyectos personales.
        Aquí hay solo algunos de todos los trabajos que he realizado. Puedes encontrar otros en mi Behance o mi Linkedin,
        pero se centran en estos "trabajos de artista" más que en el desarrollo de software.   
      </p>
      </div>

      <GalleryGrid/>
    </section>
  )
}